name: Find Cheap Trips

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  scrape-trips:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out the code from the 'main' branch
      - name: Checkout repository code
        uses: actions/checkout@v4
        # No 'ref' needed, it defaults to the branch the workflow is on

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies
        run: poetry install

      # 4. Install browser for Playwright
      - name: Install Playwright Browsers
        run: poetry run playwright install chromium

      # 5. Create config.json using the secret
      - name: Create config.json from secrets
        run: |
          cat <<EOF > config.json
          {
            "api_settings": {
              "provider": "openrouter",
              "models": { "openrouter": { "default": "deepseek/deepseek-r1-0528:free" }},
              "keys": { "openrouter_key": "${{ secrets.OPENROUTER_KEY }}" }
            },
            "search_parameters": {
              "origin_city_id": "warsaw-poland",
              "days_to_search": 20,
              "start_date": "2025-07-25",
              "max_trip_duration_days": 3,
              "num_adults": 2,
              "min_exploration_hours": 20,
              "cookie_wait_seconds": 8,
              "day_starts_at_hour": 8,
              "day_ends_at_hour": 22,
              "airport_buffer_hours": 2
            },
            "file_paths": {
              "log_file": "run_log.txt",
              "results_file": "final_trips.json"
            },
            "destinations": {
              "austria": { "enabled": true, "cities": { "vienna-austria": "Vienna" }},
              "belgium": { "enabled": true, "cities": { "brussels-belgium": "Brussels", "charleroi-belgium": "Charleroi" }},
              "croatia": { "enabled": true, "cities": { "zagreb-croatia": "Zagreb", "split-croatia": "Split", "dubrovnik-croatia": "Dubrovnik" }},
              "czechia": { "enabled": true, "cities": { "prague-czechia": "Prague" }},
              "denmark": { "enabled": true, "cities": { "copenhagen-denmark": "Copenhagen", "billund-denmark": "Billund" }},
              "france": { "enabled": true, "cities": { "paris-france": "Paris", "nice-france": "Nice", "marseille-france": "Marseille", "lyon-france": "Lyon" }},
              "germany": { "enabled": true, "cities": { "berlin-germany": "Berlin", "munich-germany": "Munich", "frankfurt-germany": "Frankfurt", "hamburg-germany": "Hamburg" }},
              "greece": { "enabled": true, "cities": { "athens-greece": "Athens", "thessaloniki-greece": "Thessaloniki", "heraklion-greece": "Heraklion (Crete)" }},
              "hungary": { "enabled": true, "cities": { "budapest-hungary": "Budapest" }},
              "italy": { "enabled": true, "cities": { "rome-italy": "Rome", "milan-italy": "Milan", "venice-italy": "Venice", "bologna-italy": "Bologna" }},
              "netherlands": { "enabled": true, "cities": { "amsterdam-netherlands": "Amsterdam", "eindhoven-netherlands": "Eindhoven" }},
              "norway": { "enabled": true, "cities": { "oslo-norway": "Oslo", "bergen-norway": "Bergen" }},
              "portugal": { "enabled": true, "cities": { "lisbon-portugal": "Lisbon", "porto-portugal": "Porto", "faro-portugal": "Faro" }},
              "spain": { "enabled": true, "cities": { "madrid-spain": "Madrid", "barcelona-spain": "Barcelona", "palma-mallorca-spain": "Palma de Mallorca", "malaga-spain": "Málaga" }},
              "sweden": { "enabled": true, "cities": { "stockholm-sweden": "Stockholm", "gothenburg-sweden": "Gothenburg" }},
              "switzerland": { "enabled": true, "cities": { "zurich-switzerland": "Zürich", "geneva-switzerland": "Geneva", "basel-switzerland": "Basel" }}
            }
          }
          EOF
      
      # 6. Run the main script
      - name: Run the trip scraper
        run: poetry run python main_controller.py

      # 7. Upload the results file
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: trip-results
          path: final_trips.json